language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements/dev.txt
  - pip install .
  - pip install Django==$DJANGO_VERSION
env:
  - SKIP_COVERAGE=1 SKIP_INSTALL=1 DJANGO_VERSION=1.4.10
  - SKIP_COVERAGE=1 SKIP_INSTALL=1 DJANGO_VERSION=1.3.7
script: fab test
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#armstrongcms"
